name: Executar Testes Backend e Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependências do Backend
        run: |
          cd api
          npm install

      - name: Executar testes do Backend
        run: |
          cd api
          npm test

      - name: Instalar dependências do Frontend
        run: |
          cd client
          npm install

      - name: Iniciar servidor do Frontend
        run: |
          cd client
          npm run serve &

      - name: Aguardar o servidor do Frontend
        run: npx wait-on http://localhost:8080

      - name: Executar testes com Cypress
        run: |
          cd client
          npx cypress run
